Fixes #112
USGS-WiM/StreamStats-National pull request #116
Opened 2021-11-08 21:39 UTC by harper-wavra

Added poly_IncidentName, poly_GISAcres, poly_DateCurrent, irwin_FireCause, irwin_FireCauseGeneral, irwin_FireDiscoveryDateTime, irwin_FireOutDateTime, irwin_UniqueFireIdentifier to `shownFields`.

Updated the active fire perimeters layer to 2021 Wildland Fire Perimeters to date per kitty's request.

2021-11-08 21:54 UTC, amedenblik requested changes
Looks good! I have two small comments.

2021-11-08 21:54 UTC, amedenblik commented on src/app/map/map.component.ts
>                    this.addLayers('Archived WildFire Perimeters');
Can you please rename to "Archived Wildfire Perimeters" in the config.json (and elsewhere in the code)?

2021-11-08 21:54 UTC, amedenblik commented on src/assets/config.json
> +        "name": "2021 Wildfires Perimeters",
Can you please rename to "2021 Wildfire Perimeters"? Sorry, this was my typo!

2021-11-09 19:49 UTC, harper-wavra commented
I added those new labels to the popups, I was having some trouble, and spending too much time to get them to show up the same way in the report, so I thought we could create another issue and come back to that.

2021-11-09 21:51 UTC, amedenblik commented
I'm wondering if we should roll back the new labels in the popups, so that the labels in the popups and report are consistent. Thoughts?

2021-11-09 22:25 UTC, harper-wavra commented
Yeah that might be best. It wasnt hard to add it in, so when we have more time to look at the report/html we just add them back.

2021-11-10 17:28 UTC, amedenblik approved these changes

2021-11-10 17:28 UTC, merged