Closes #114 - Add gages to Fire Hydrology - Query by Fire Perimeter workflow
USGS-WiM/StreamStats-National pull request #262
Opened 2022-12-19 18:49 UTC by amedenblik

Closes #114

2022-12-20 16:31 UTC, harper-wavra requested changes
I know it hasn't passed linting yet but thought I would review now as I will be out for a bit after today.

Working great! Just a couple comments, 

-The gage table seems to be a bit off. 
![image](https://user-images.githubusercontent.com/59063181/208715850-57b2b738-c7f5-4ba0-84fe-8a3538d00edf.png)
- a couple console.logs 

I also wonder if right before we merge this, we update the polygon endpoints & change the `nldiPolygonQuery` url back so everything is done in this one issue

2022-12-20 16:31 UTC, harper-wavra commented on src/app/map/map.component.ts
> +    this._mapService.map.fitBounds(this.firePerimeterLayer.getBounds(), {padding: [75,75]});
There seem to be console errors thrown at this line, maybe we can check if there is a `firePerimeterLayer` before fitting bounds. 
![image](https://user-images.githubusercontent.com/59063181/208715118-d16ae058-a96b-4b0f-be77-a6a415c4643b.png)

2023-01-07 01:43 UTC, amedenblik commented
I have addressed linting and your review. I also reverted `nldiPolygonQuery` back to `https://streamstats.usgs.gov/nldipolygonservices/nldi_poly_query`. Let's ping @Anders-Hopkins to rename `https://streamstats.usgs.gov/nldipolygonservices/nldi_poly_query_new` to `https://streamstats.usgs.gov/nldipolygonservices/nldi_poly_query` before we merge this PR.

2023-01-11 17:54 UTC, amedenblik commented
@harper-wavra this branch is working again and ready to be reviewed

2023-01-11 18:30 UTC, harper-wavra requested changes
I tested each endpoint. Delineation and Query by fire perimeter both looked & worked well. Query by basin seems to be getting hung up though. I tried on the https://test.streamstats.usgs.gov/national/ site and it's working there, so I think it might be related to changes in this branch.

2023-01-11 19:12 UTC, amedenblik commented
I pulled in the `dev` branch, which fixed the Query by Basin issues. Reminder- let's not merge until nldi_poly_query is renamed.

2023-01-11 20:22 UTC, harper-wavra approved these changes
Looks good!

2023-01-11 20:23 UTC, merged