Closes Issue #70 - adding toggleable layers
USGS-WiM/StreamStats-National pull request #97
Opened 2021-10-01 14:14 UTC by ltmetz

2021-10-01 18:59 UTC, amedenblik requested changes
Awesome work! This will be super helpful! Some things I noticed:

- [x] When I uncheck layers, click the "X" to close the Map Layers popout, and click the icon to open the Map Layers popout again, all the layers are checked again.  

- [ ] Allow the user to click on the name of the layer to check/uncheck the checkbox. You can do this by included the <input /> field inside the <label></label> tags. Or, you can do this by using the "for" attribute on the <label> tag. 

- [ ] When I click Report Builder and select a Fire Hydro workflow, the workflow layers are added to the Map Layers popout. Then I click the "X" to close the Report Builder popout, and the workflow has been exited out of, but that workflow's map layers are still in the Map Layers popout. So if I again choose a Fire Hydro workflow, now two copies of the Fire Hydro workflow layers appear in the Map Layers popout. I think this is more of an issue that clicking "X" to close the Report Builder popout shouldn't exit out of the current workflow-- see issue #88.

2021-10-01 18:59 UTC, amedenblik commented on src/app/sidebar-left/sidebar-left.component.html
> +							<label  style="font-size: small;">(active at zoom level {{overlay[1]}} or greater)</label>
We can omit the text "(active at zoom level X or greater)"-- I think we can rely on the disabled checkboxes based on zoom level

2021-10-01 18:59 UTC, amedenblik commented on src/app/sidebar-left/sidebar-left.component.html
> +						<input type="checkbox" name="activeWorkflowLayers" value="layer.name" (change)="updateActiveLayer(layer.name)" [checked]="true"> {{layer.name}}
Some of the workflow layers have a minZoom requirement (example: Burn Severity has minZoom 10), so we want to disable those checkboxes when applicable too.

2021-10-01 18:59 UTC, amedenblik commented on src/app/sidebar-left/sidebar-left.component.html
> +					<h4>Base Layers</h4>
Rename "Base Layers" to "Application Layers" as to not cause confusion with Base Maps.

2021-10-05 15:03 UTC, ltmetz commented
Third checkmark is now issue #100

2021-10-05 17:03 UTC, amedenblik approved these changes
Confirmed that comments were addressed ✅

2021-10-05 17:03 UTC, merged